# Generated by Django 5.1.7 on 2025-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0002_registeruser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='social_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
